# name of workflow
name: hello
# runs on a trigger
on:
   workflow_dispatch: 
# there are jobs 
jobs:
#name of jobs
  greet:
#this is runner each jobs run on runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello"
      - name: say hello to username
        run: echo "hello $USER"
  details:
      runs-on: ubuntu-latest
      steps:
        - name: python version
          run: python --version
